export const MENU_FILTER_CLICK = "MENU_FILTER_CLICK";
export const RECEIVE_SKILLS = "RECEIVE_SKILLS";
export const REQUEST_SKILLS = "REQUEST_SKILLS";

export const FETCHING_DATA = "FETCHING_DATA";
export const RECEIVE_DATA = "RECEIVE_DATA";
